data:
  dataset: "imagewoof"
  limit: -1  # Limit number of examples. -1 = use all data
  val_ratio: 0.1
model: # MAE
  patch_size: 16
  mask_ratio: 0.1
  encoder_layers: 6
  encoder_num_heads: 6
  encoder_hidden_dim: 384
  encoder_mlp_dim: 1536
  decoder_layers: 3
  decoder_num_heads: 3
  decoder_hidden_dim: 192
  decoder_mlp_dim: 768
batch_size: 256
optimizer: # Adam
  lr: 0.00015
  betas:
    - 0.9
    - 0.95
  weight_decay: 0.05
scheduler:
  T_max: 3000
  eta_min: 0.000000001
random_seed: 0
lookahead: 150