data:
    dataset: "cifar10"
    limit: -1  # Limit number of examples. -1 = use all data
    val_ratio: 0.2
model:  # MAE
    patch_size: 4
    mask_ratio: 0.5
    encoder_layers: 8
    encoder_num_heads: 8
    encoder_hidden_dim: 256
    encoder_mlp_dim: 1024
    decoder_layers: 4
    decoder_num_heads: 8
    decoder_hidden_dim: 64
    decoder_mlp_dim: 256
batch_size: 512
optimizer:  # Adam
    lr: 0.001
    betas:
        - 0.9
        - 0.95
    weight_decay: 0.05
scheduler:  
    T_max: 2000
    eta_min: 0.000000001 
random_seed: 0
lookahead: 50