data:
    dataset: "coco"
    limit: 100  # Limit number of examples. -1 = use all data
    val_ratio: 0.1
model:  # MAE
    patch_size: 16
    mask_ratio: 0.7
    encoder_layers: 12
    encoder_num_heads: 12
    encoder_hidden_dim: 768
    encoder_mlp_dim: 3072
    decoder_layers: 8
    decoder_num_heads: 8
    decoder_hidden_dim: 256
    decoder_mlp_dim: 1024
batch_size: 32
optimizer:  # Adam
    lr: 0.01
    betas:
        - 0.9
        - 0.95
    weight_decay: 0.05
scheduler:  
    T_max: 2000
    eta_min: 0.000000001 
random_seed: 0
lookahead: 1