data:
    dataset: "imagenette"
    limit: -1  # Limit number of examples. -1 = use all data
    val_ratio: 0.1
model:  # MAE
    patch_size: 16
    mask_ratio: 0.7
    encoder_layers: 8
    encoder_num_heads: 8
    encoder_hidden_dim: 512
    encoder_mlp_dim: 2048
    decoder_layers: 6
    decoder_num_heads: 6
    decoder_hidden_dim: 128
    decoder_mlp_dim: 768
batch_size: 64
optimizer:  # Adam
    lr: 0.001
    betas:
        - 0.9
        - 0.95
    weight_decay: 0.05
scheduler:  
    T_max: 2000
    eta_min: 0.000000001 
random_seed: 0
lookahead: 50